version: "3.8"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5000:5000"
      - "127.0.0.1:5432:5432"
  migration:
    image: postgres:latest
    restart: on-failure
    network_mode: service:db
    depends_on:
      - db
    entrypoint:
      - "/bin/bash"
      - "-e"
      - "-c"
      - "sleep 4 && cd /tmp && psql -h localhost -U postgres -f db/schema.sql -f db/data.sql -f db/functions.sql"
    volumes:
      - "./db/:/tmp/db"
  postgraphile:
    build: 
      context: .
      dockerfile: Postgraphile.Dockerfile
    restart: unless-stopped
    network_mode: service:db
    depends_on:
      - db
    environment:
      PGPASSWORD: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGHOST: localhost
    volumes:
      - "./postgraphile.tags.json5:/postgraphile/postgraphile.tags.json5"
    command:
      [
        "--enhance-graphiql",
        "--allow-explain",
        "--port",
        "5000",
        "--schema",
        "public",
        "--watch",
        "--append-plugins",
        "postgraphile-plugin-connection-filter",
      ]
